import React, { useState } from "react";
import {
  FiArrowLeft,
  FiCreditCard,
  FiLock,
  FiStar,
  FiUser,
} from "react-icons/fi";
import axios from "axios";
import { useSelector } from "react-redux";

const course = {
  _id: "64f0c0b9d2a2c9b1f0e4a123", // replace with real course id
  category: { name: "Web Development" },
  instructor: { name: "Anjali Sharma", bio: "Senior Developer" },
  title: "Master the MERN Stack - From Beginner to Expert",
  description: "Learn to build full-stack applications using MongoDB, Express.js, React, and Node.js.",
  originalPrice: 12999,
  discountPercentage: 60,
  price: 5199,
  stats: { rating: 4.8, students: 3250, reviews: 420 },
};

function Checkout() {
  const [loading, setLoading] = useState(false);
  const userId = useSelector(state => state.login.userId);
  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement("script");
      script.src = "https://checkout.razorpay.com/v1/checkout.js";
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handleRazorpayPayment = async () => {
    try {
      setLoading(true);
      const sdkLoaded = await loadRazorpayScript();
      if (!sdkLoaded) return alert("Razorpay SDK failed to load.");

      // Create order on the server
      const orderRes = await axios.post(`${import.meta.env.VITE_BASE_URL}/api/payment/order`, {
        amount: course.price,
        currency: "INR",
      });

      if (!orderRes.data.success) {
        setLoading(false);
        return alert("Order creation failed on server.");
      }

      const { id: order_id, amount, currency } = orderRes.data;

      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID,
        amount: amount,
        currency: currency,
        name: "CoderHaveli",
        description: course.title,
        order_id, // pass the order id generated by the server
        method: {
          upi: true,
          card: true,
          netbanking: true,
          wallet: true,
        },
        prefill: {
          name: "Prashant Sharma",
          email: "prashant@example.com",
          contact: "9999999999",
        },
        notes: {
          courseId: course._id,
        },
        theme: {
          color: "#4F46E5",
        },
        handler: async function (response) {
          // response contains razorpay_payment_id, razorpay_order_id, razorpay_signature
          try {
            // include userId and courseId so backend can save subscription
            const payload = {
              ...response,
              userId: userId, // set a test user in env or pass real user id
              courseId: course._id,
              amount: course.price,
            };

            const verifyRes = await axios.post(`${import.meta.env.VITE_BASE_URL}/api/payment/verify`, payload);

            if (verifyRes.data.success) {
              alert("Payment successful and verified! 🎉");
              console.log("verifyRes.data:", verifyRes.data);
            } else {
              alert("Payment verification failed on server.");
              console.error("verify failed", verifyRes.data);
            }
          } catch (err) {
            console.error(err);
            alert("Server verification error");
          } finally {
            setLoading(false);
          }
        },
      };

      const rzp = new window.Razorpay(options);

      rzp.on("payment.failed", function (resp) {
        alert(`Payment failed: ${resp.error.description}`);
        setLoading(false);
      });

      rzp.open();
    } catch (err) {
      console.error(err);
      alert("Something went wrong");
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded shadow p-6">
        <header className="mb-6">
          <h2 className="text-lg font-semibold cursor-pointer" onClick={() => window.history.back()}>
            <FiArrowLeft className="inline mr-2" /> Back to course
          </h2>
        </header>

        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <h1 className="text-2xl font-bold">{course.title}</h1>
            <p className="mt-2 text-sm text-gray-600">{course.description}</p>
            <div className="mt-4 text-3xl font-bold">₹{course.price.toLocaleString()}</div>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-3">Complete Enrollment</h3>
            <button
              onClick={handleRazorpayPayment}
              disabled={loading}
              className="w-full bg-indigo-600 text-white py-3 rounded-lg"
            >
              {loading ? "Processing..." : `Pay ₹${course.price.toLocaleString()} with Razorpay`}
            </button>
            <p className="text-xs text-gray-500 mt-2">You will be redirected to Razorpay’s secure payment page</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Checkout;